import React,{useEffect,useRef,useState} from 'react';
import {Provider,useApp,useHash,type Toast,type EditModal,type Confirm} from './store';
import {Editor} from './forms';
import {Icon,Logo,Modal} from './ui';
import {Dashboard,Inventory,Repairs,Parts,ActivityPage} from './pages';
import {ConsoleDetail,RepairDetail,NotFound} from './details';
import {active} from './domain';
import {Settings} from './admin-settings';
import {SessionActions} from './auth';
const nav=[{path:'/dashboard',label:'Tableau de bord',icon:'dashboard'},{path:'/inventory',label:'Mes consoles',icon:'gamepad'},{path:'/repairs',label:'L’atelier',icon:'wrench'},{path:'/parts',label:'Pièces détachées',icon:'package'},{path:'/activity',label:'Journal d’activité',icon:'activity'}];
function Shell(){
 const {data,go,edit,exportData,storageError}=useApp();const route=useHash(),[pathname,searchPart='']=route.split('?'),query=new URLSearchParams(searchPart),[mobile,setMobile]=useState(false),[search,setSearch]=useState(''),[focused,setFocused]=useState(false);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{setMobile(false);setSearch('');setFocused(false);},[route]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.current?.focus();}};document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h);},[]);
 useEffect(()=>{document.title=`${data.settings.workshop} · ${nav.find(n=>pathname.startsWith(n.path))?.label||'Votre atelier'}`;},[pathname,data.settings.workshop]);
 const normal=search.trim().toLowerCase();const consoleResults=normal?data.consoles.filter(c=>`${c.brand} ${c.model} ${c.code} ${c.serial}`.toLowerCase().includes(normal)).slice(0,4):[];const repairResults=normal?data.repairs.filter(r=>`${r.code} ${r.title} ${data.consoles.find(c=>c.id===r.consoleId)?.model||''}`.toLowerCase().includes(normal)).slice(0,3):[];
 const current=nav.find(n=>pathname.startsWith(n.path));const running=data.repairs.filter(active).length;const timer=data.repairs.find(r=>r.timerStartedAt);
 const segment=pathname.split('/').filter(Boolean);let content:React.ReactNode;
 if(pathname==='/'||pathname==='/dashboard')content=<Dashboard/>;else if(pathname==='/inventory')content=<Inventory query={query}/>;else if(segment[0]==='inventory'&&segment.length===2)content=<ConsoleDetail key={segment[1]} id={segment[1]}/>;else if(pathname==='/repairs')content=<Repairs query={query}/>;else if(segment[0]==='repairs'&&segment.length===2)content=<RepairDetail key={segment[1]} id={segment[1]}/>;else if(pathname==='/parts')content=<Parts query={query}/>;else if(pathname==='/activity')content=<ActivityPage/>;else if(pathname==='/settings')content=<Settings/>;else content=<NotFound label="Cette page n’existe pas"/>;
 return <div className="app-layout"><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus();}}>Aller au contenu</a>{mobile&&<button className="sidebar-overlay" aria-label="Fermer le menu" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'mobile-open':''}`}><a href="#/dashboard" className="brand" aria-label="La Clinique Rétro, accueil"><Logo/><div>{data.settings.workshop==='La Clinique Rétro'?<><strong>La Clinique</strong><span>Rétro<span className="brand-dot">.</span></span></>:<strong className="custom-workshop">{data.settings.workshop}</strong>}</div></a><div className="sidebar-divider"/><span className="nav-section-label">MON ESPACE</span><nav aria-label="Navigation principale">{nav.map(n=><a key={n.path} href={'#'+n.path} className={pathname.startsWith(n.path)?'active':''} aria-current={pathname.startsWith(n.path)?'page':undefined}><Icon name={n.icon} size={20}/><span>{n.label}</span>{n.path==='/repairs'&&running>0&&<span className="nav-count">{running}</span>}</a>)}</nav><button className="sidebar-add" onClick={()=>edit({type:'console'})}><Icon name="plus" size={17}/>Ajouter une console</button>
 <div className="sidebar-bottom"><div className="sidebar-motto"><div className="motto-illustration"><Icon name="gamepad" size={35}/><span>+</span><span>+</span></div><strong>Réparer. Préserver. Rejouer.</strong><p>Les belles histoires<br/>n’ont pas de fin de vie.</p></div><a href="#/settings" className={`settings-link ${pathname==='/settings'?'active':''}`}><Icon name="settings" size={19}/>Réglages & sauvegardes</a><div className="sidebar-user"><span className="avatar">{(data.settings.owner||'A').slice(0,1).toUpperCase()}</span><div><strong>{data.settings.owner||'Mon atelier'}</strong><span>Accès administrateur</span></div><span className="local-dot" title="Données enregistrées sur le serveur"/></div></div></aside>
 <div className="workspace"><header className="topbar"><div className="topbar-left"><button className="icon-btn mobile-menu" aria-label="Ouvrir le menu" onClick={()=>setMobile(true)}><Icon name="menu"/></button><span className="breadcrumb">Mon atelier<Icon name="right" size={13}/><strong>{current?.label||'Réglages'}</strong></span></div><div className="global-search"><Icon name="search" size={17}/><input ref={input} aria-label="Recherche globale" value={search} onChange={e=>setSearch(e.target.value)} onFocus={()=>setFocused(true)} onBlur={()=>setTimeout(()=>setFocused(false),150)} onKeyDown={e=>{if(e.key==='Escape'){setFocused(false);input.current?.blur();}if(e.key==='Enter'){if(consoleResults[0])go('/inventory/'+consoleResults[0].id);else if(repairResults[0])go('/repairs/'+repairResults[0].id);}}} placeholder="Rechercher dans la clinique…"/><kbd>⌘ K</kbd>{focused&&normal&&<div className="search-results">{!!consoleResults.length&&<h4>CONSOLES</h4>}{consoleResults.map(c=><button key={c.id} onMouseDown={e=>e.preventDefault()} onClick={()=>go('/inventory/'+c.id)}><Icon name="gamepad" size={17}/><div><strong>{c.brand} {c.model}</strong><small>{c.code} · {c.serial}</small></div><Icon name="right" size={14}/></button>)}{!!repairResults.length&&<h4>DOSSIERS</h4>}{repairResults.map(r=><button key={r.id} onMouseDown={e=>e.preventDefault()} onClick={()=>go('/repairs/'+r.id)}><Icon name="wrench" size={17}/><div><strong>{r.title}</strong><small>{r.code}</small></div><Icon name="right" size={14}/></button>)}{!consoleResults.length&&!repairResults.length&&<p>Aucun résultat pour « {search} ».</p>}</div>}</div><div className="topbar-right"><SessionActions/>{timer?<button className="timer-top" onClick={()=>go('/repairs/'+timer.id)}><span/><Icon name="clock" size={15}/>{timer.code}</button>:<span className="local-status"><span/>Sauvegarde serveur</span>}<button className="header-avatar" aria-label="Ouvrir les réglages" onClick={()=>go('/settings')}>{(data.settings.owner||'A').slice(0,1).toUpperCase()}</button></div></header>
 {storageError&&<div role="alert" className="storage-error"><Icon name="alert" size={19}/><span>{storageError}</span><button onClick={exportData}>Exporter ma session</button></div>}
 <main id="main" className="main-content" tabIndex={-1}>{data.settings.demo&&<div className="demo-ribbon screen-only"><span><i/>ATELIER DE DÉMONSTRATION</span><p>Des consoles et des dossiers fictifs pour découvrir la clinique.</p><button onClick={()=>go('/settings')}>Créer mon atelier<Icon name="arrow" size={14}/></button></div>}{content}</main></div></div>;
}
function ConfirmDialog({confirm,onClose}:{confirm:NonNullable<Confirm>;onClose:()=>void}){const [value,setValue]=useState('');return <Modal title={confirm.title} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(confirm.verify&&value!==confirm.verify)return;const result=confirm.run();if(result!==false)onClose();}}><div className="modal-body"><div className={`confirm-symbol ${confirm.destructive?'orange':'teal'}`}><Icon name={confirm.destructive?'alert':'info'} size={27}/></div><p className="confirm-body">{confirm.body}</p>{confirm.verify&&<label className="field"><span>Saisissez <strong>{confirm.verify}</strong> pour confirmer.</span><input value={value} onChange={e=>setValue(e.target.value)} autoComplete="off" spellCheck={false} aria-label="Mot de confirmation" required/></label>}</div><div className="modal-footer"><button type="button" className="btn secondary" onClick={onClose}>Annuler</button><button type="submit" className={`btn ${confirm.destructive?'danger':'primary'}`} disabled={!!confirm.verify&&value!==confirm.verify}>{confirm.label||'Confirmer'}</button></div></form></Modal>;}
export function App(){const [toast,setToast]=useState<Toast|null>(null),[editor,setEditor]=useState<EditModal>(null),[confirm,setConfirm]=useState<Confirm>(null);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),toast.error?9000:5000);return()=>clearTimeout(t);},[toast]);return <Provider showToast={setToast} edit={setEditor} ask={setConfirm}><Shell/>{editor&&<Editor key={`${editor.type}:${editor.id||'new'}`} modal={editor} onClose={()=>setEditor(null)}/>} {confirm&&<ConfirmDialog key={confirm.title} confirm={confirm} onClose={()=>setConfirm(null)}/>} {toast&&<div className={`toast ${toast.error?'error':''}`} role={toast.error?'alert':'status'}><span><Icon name={toast.error?'alert':'check'} size={19}/></span><p>{toast.message}</p><button className="icon-btn" aria-label="Fermer la notification" onClick={()=>setToast(null)}><Icon name="close" size={16}/></button></div>}</Provider>;}
export class ErrorBoundary extends React.Component<{children:React.ReactNode},{error:string}> {state={error:''};static getDerivedStateFromError(error:Error){return{error:error.message};}render(){return this.state.error?<div className="recovery"><h1>L’atelier a rencontré une erreur.</h1><p>Les données déjà confirmées restent sur le serveur. Rechargez la page pour réessayer.</p><button className="btn primary" onClick={()=>location.reload()}>Recharger l’atelier</button></div>:this.props.children;}}
