import React,{useEffect,useRef,useState} from 'react';
import {useApp} from './store';
import {Icon,ConsoleVisual,Badge,StateBadge,StageBadge,PriorityBadge,Empty,Panel,Timeline,Field} from './ui';
import {text,number} from './forms';
import {type Repair,type Stage,type ConsoleState,type Store,STAGES,STATES,PRIORITIES,active,partsCost,totalMinutes,minutesFmt,compactMoney,money,dateFmt,today,overdue,moveRepair,consoleInvestment,emptyStore,validateStore,addEvent} from './domain';
import {demoStore} from './seed';
export function PageHeader({eyebrow,title,description,children}:{eyebrow:string;title:string;description?:string;children?:React.ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{children&&<div className="heading-actions">{children}</div>}</div>;}
function Metric({label,value,detail,icon,tone='teal',onClick}:{label:string;value:string|number;detail:string;icon:string;tone?:string;onClick?:()=>void}){return <button className="metric" onClick={onClick}><div className="metric-top"><span>{label}</span><span className={`metric-icon ${tone}`}><Icon name={icon} size={19}/></span></div><strong>{value}</strong><small>{detail}</small></button>;}
export function RepairRows({repairs,compact=false}:{repairs:Repair[];compact?:boolean}){
 const {data,go}=useApp();return <div className="table-scroll"><table className={`data-table repair-table ${compact?'compact':''}`}><thead><tr><th>Console / intervention</th><th>Étape</th>{!compact&&<th>Priorité</th>}<th>Échéance</th><th aria-label="Ouvrir"/></tr></thead><tbody>{repairs.map(r=>{const c=data.consoles.find(c=>c.id===r.consoleId)!;return <tr key={r.id}><td><div className="table-item"><div className={`mini-visual art-${c.illustration}`}><ConsoleVisual item={c} small/></div><div><button className="table-title" onClick={()=>go('/repairs/'+r.id)}>{c.brand} {c.model}</button><span>{r.title}</span><small className="mono">{r.code}</small></div></div></td><td><StageBadge stage={r.stage}/></td>{!compact&&<td><PriorityBadge priority={r.priority}/></td>}<td><span className={overdue(r)?'overdue':'muted'}>{r.dueDate?dateFmt(r.dueDate):'Non définie'}</span>{overdue(r)&&<small className="overdue block">Échéance dépassée</small>}</td><td><button className="icon-btn" title={`Ouvrir ${r.code}`} onClick={()=>go('/repairs/'+r.id)}><Icon name="right" size={17}/></button></td></tr>;})}</tbody></table></div>;
}
export function Dashboard(){
 const {data,go,edit}=useApp();const consoles=data.consoles.filter(c=>!c.archived),running=data.repairs.filter(active),done=data.repairs.filter(r=>r.stage==='terminee'),low=data.parts.filter(p=>p.quantity<=p.threshold);
 const untested=consoles.filter(c=>c.state==='a-tester');const inTests=running.filter(r=>r.stage==='tests');const featured=running.find(r=>r.stage==='reparation')||running[0];const featuredConsole=featured&&consoles.find(c=>c.id===featured.consoleId);const priorityOrder={urgente:0,haute:1,normale:2,basse:3};
 const urgent=[...running].sort((a,b)=>priorityOrder[a.priority]-priorityOrder[b.priority]||(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).slice(0,4);
 const percent=consoles.length?Math.round(consoles.filter(c=>c.state==='fonctionnelle').length/consoles.length*100):0;
 return <><PageHeader eyebrow="VOTRE ESPACE ATELIER" title="L’atelier, en un coup d’œil." description="Chaque console mérite une seconde vie."><button className="btn secondary" onClick={()=>edit({type:'console'})}><Icon name="plus" size={18}/>Ajouter une console</button><button className="btn primary" onClick={()=>edit({type:'repair'})}><Icon name="wrench" size={17}/>Nouvelle réparation</button></PageHeader>
 <div className="metrics"><Metric label="Consoles en collection" value={consoles.length} detail={`${consoles.filter(c=>c.state==='fonctionnelle').length} fonctionnelles · ${untested.length} à tester`} icon="gamepad" onClick={()=>go('/inventory')}/><Metric label="À l’atelier" value={running.length} detail={`${running.filter(r=>r.stage==='attente-pieces'||r.stage==='a-commander').length} en attente de pièces`} icon="wrench" tone="blue" onClick={()=>go('/repairs')}/><Metric label="Réparations terminées" value={done.length} detail="Des histoires qui continuent" icon="heart" tone="purple" onClick={()=>go('/repairs?view=closed')}/><Metric label="Valeur de la collection" value={compactMoney(consoles.reduce((s,c)=>s+c.estimatedValue,0))} detail="Selon vos estimations personnelles" icon="euro" tone="amber" onClick={()=>go('/inventory')}/></div>
 <div className="dashboard-hero"><div className="hero-copy"><span className="hero-kicker"><span/> LA PASSION, ÇA SE RÉPARE.</span><h2>De retour<br/>dans la partie.</h2><p>Un diagnostic, un peu de patience,<br/>et de nouvelles heures de jeu.</p><button className="hero-link" onClick={()=>go('/repairs')}>Entrer dans l’atelier<Icon name="arrow" size={17}/></button></div><div className="hero-decor" aria-hidden="true"><span className="pixel pixel-1"/><span className="pixel pixel-2"/><span className="pixel pixel-3"/><span className="orbit"/></div>{featured&&featuredConsole?<button className="hero-feature" onClick={()=>go('/repairs/'+featured.id)}><span className="feature-label"><span/> SUR L’ÉTABLI</span><div className="hero-art"><ConsoleVisual item={featuredConsole}/></div><div className="feature-bottom"><div><strong>{featuredConsole.brand} {featuredConsole.model}</strong><small>{featured.title}</small></div><span className="circle-arrow"><Icon name="arrow"/></span></div></button>:<div className="hero-empty"><Icon name="gamepad" size={94}/><p>L’aventure commence avec<br/>votre première console.</p></div>}</div>
 <div className="dashboard-main"><Panel title="Les dossiers à suivre" aside={<button className="text-link" onClick={()=>go('/repairs')}>Tout l’atelier<Icon name="arrow" size={15}/></button>}>{urgent.length?<RepairRows repairs={urgent} compact/>:<Empty title="L’établi est libre" action={<button className="btn primary small" onClick={()=>edit({type:'repair'})}>Ouvrir un dossier</button>}>Aucune réparation en cours pour le moment.</Empty>}</Panel><Panel title="À ne pas oublier" className="attention-panel"><button className="attention-item" onClick={()=>go('/parts?low=1')}><span className="attention-icon orange"><Icon name="package"/></span><div><strong>{low.length} référence{low.length>1?'s':''} à réapprovisionner</strong><p>{low.length?low.slice(0,2).map(p=>p.reference).join(' · '):'Les niveaux de stock sont bons.'}</p></div><Icon name="right" size={16}/></button><button className="attention-item" onClick={()=>go('/repairs?stage=tests')}><span className="attention-icon teal"><Icon name="checklist"/></span><div><strong>{inTests.length} dossier{inTests.length>1?'s':''} en phase de test</strong><p>Dernière ligne droite avant la reprise.</p></div><Icon name="right" size={16}/></button><button className="attention-item" onClick={()=>go('/inventory?state=a-tester')}><span className="attention-icon purple"><Icon name="gamepad"/></span><div><strong>{untested.length} console{untested.length>1?'s':''} à tester</strong><p>Un premier bilan reste à faire.</p></div><Icon name="right" size={16}/></button><div className="collection-health"><div><span>Une collection en pleine forme</span><strong>{percent}%</strong></div><div className="progress-track"><span style={{width:percent+'%'}}/></div><p>de vos consoles sont fonctionnelles</p></div></Panel></div>
 <div className="dashboard-bottom"><Panel title="Dernières arrivées" aside={<button className="text-link" onClick={()=>go('/inventory')}>L’inventaire<Icon name="arrow" size={15}/></button>}>{consoles.length?<div className="arrivals">{[...consoles].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,3).map(c=><button className="arrival" key={c.id} onClick={()=>go('/inventory/'+c.id)}><div className={`arrival-visual art-${c.illustration}`}><ConsoleVisual item={c}/></div><strong>{c.model}</strong><small>{c.brand} · {c.code}</small><StateBadge state={c.state}/></button>)}</div>:<Empty title="Votre collection vous attend" icon="gamepad">Ajoutez votre première console pour commencer.</Empty>}</Panel><Panel title="Le journal de l’atelier" aside={<button className="text-link" onClick={()=>go('/activity')}>Voir tout<Icon name="arrow" size={15}/></button>}>{data.events.length?<Timeline events={data.events} limit={3} lookup={id=>data.consoles.find(c=>c.id===id)?.model||''} onOpen={e=>go(e.repairId?'/repairs/'+e.repairId:'/inventory/'+e.consoleId)}/>:<Empty title="Une page blanche" icon="note">Vos interventions seront consignées ici.</Empty>}</Panel></div>
 <div className="page-foot"><Icon name="shield" size={14}/> Votre atelier personnel. Vos données restent dans ce navigateur.<button className="text-link" onClick={()=>go('/settings')}>Gérer les sauvegardes</button></div></>;
}
export function Inventory({query}:{query:URLSearchParams}){
 const {data,go,edit,exportInventory}=useApp();const [search,setSearch]=useState(''),[state,setState]=useState(query.get('state')||'all'),[brand,setBrand]=useState('all'),[layout,setLayout]=useState<'grid'|'list'>('grid'),[sort,setSort]=useState('recent'),[archived,setArchived]=useState(false);
 useEffect(()=>setState(query.get('state')||'all'),[query.toString()]);
 const filtered=data.consoles.filter(c=>c.archived===archived&&(state==='all'||c.state===state)&&(brand==='all'||c.brand===brand)&&[c.brand,c.model,c.code,c.serial,c.location,c.variant].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?a.model.localeCompare(b.model,'fr'):sort==='value'?b.estimatedValue-a.estimatedValue:b.createdAt.localeCompare(a.createdAt));
 return <><PageHeader eyebrow="LA COLLECTION" title="L’inventaire des consoles" description={`${data.consoles.filter(c=>!c.archived).length} consoles, chacune avec son histoire.`}><button className="btn secondary" onClick={exportInventory}><Icon name="download" size={17}/>Exporter en CSV</button><button className="btn primary" onClick={()=>edit({type:'console'})}><Icon name="plus" size={18}/>Ajouter une console</button></PageHeader>
 <div className="view-tabs"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>Ma collection<span>{data.consoles.filter(c=>!c.archived).length}</span></button><button className={archived?'active':''} onClick={()=>setArchived(true)}>Archives<span>{data.consoles.filter(c=>c.archived).length}</span></button></div>
 <div className="toolbar"><div className="search-field"><Icon name="search" size={18}/><input aria-label="Rechercher dans l’inventaire" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Une console, un numéro de série…"/></div><select aria-label="Filtrer par état" value={state} onChange={e=>setState(e.target.value)}><option value="all">Tous les états</option>{Object.entries(STATES).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select aria-label="Filtrer par marque" value={brand} onChange={e=>setBrand(e.target.value)}><option value="all">Toutes les marques</option>{[...new Set(data.consoles.map(c=>c.brand))].sort().map(b=><option key={b}>{b}</option>)}</select><select aria-label="Trier l’inventaire" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Ajout récent</option><option value="name">Modèle A → Z</option><option value="value">Valeur décroissante</option></select><div className="segmented"><button className={layout==='grid'?'active':''} onClick={()=>setLayout('grid')} aria-label="Vue cartes" aria-pressed={layout==='grid'}><Icon name="grid" size={18}/></button><button className={layout==='list'?'active':''} onClick={()=>setLayout('list')} aria-label="Vue liste" aria-pressed={layout==='list'}><Icon name="list" size={19}/></button></div></div>
 <div className="results-line"><span>{filtered.length} console{filtered.length!==1?'s':''} affichée{filtered.length!==1?'s':''}</span>{(search||state!=='all'||brand!=='all')&&<button className="text-link" onClick={()=>{setSearch('');setState('all');setBrand('all');}}>Réinitialiser les filtres</button>}</div>
 {!filtered.length?<div className="panel"><Empty title={data.consoles.length?'Aucune console ne correspond':'Votre collection commence ici'} icon="gamepad" action={<button className="btn primary" onClick={()=>edit({type:'console'})}><Icon name="plus" size={17}/>Ajouter une console</button>}>{data.consoles.length?'Modifiez les filtres ou ajoutez une nouvelle console.':'Enregistrez une console et retrouvez toute son histoire au même endroit.'}</Empty></div>:layout==='grid'?<div className="console-grid">{filtered.map(c=><article className="console-card" key={c.id}><button className={`console-card-art art-${c.illustration}`} onClick={()=>go('/inventory/'+c.id)} aria-label={`Ouvrir la fiche de ${c.model}`}><span className="console-code mono">{c.code}</span><StateBadge state={c.state}/><ConsoleVisual item={c}/></button><div className="console-card-body"><div className="console-brand">{c.brand}</div><button className="console-card-title" onClick={()=>go('/inventory/'+c.id)}>{c.model}<Icon name="right" size={18}/></button><p>{c.variant||'Variante non renseignée'}</p><div className="console-card-foot"><span><Icon name="location" size={14}/>{c.location||'À ranger'}</span><strong title="Valeur estimée">{compactMoney(c.estimatedValue)}</strong></div></div></article>)}</div>:<div className="panel table-scroll"><table className="data-table"><thead><tr><th>Console</th><th>État</th><th>Emplacement</th><th>Achat</th><th>Valeur estimée</th><th/></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><div className="table-item"><div className={`mini-visual art-${c.illustration}`}><ConsoleVisual item={c} small/></div><div><button className="table-title" onClick={()=>go('/inventory/'+c.id)}>{c.brand} {c.model}</button><span>{c.variant}</span><small className="mono">{c.code}</small></div></div></td><td><StateBadge state={c.state}/></td><td>{c.location||'Non renseigné'}</td><td>{money(c.purchasePrice)}</td><td><strong>{money(c.estimatedValue)}</strong></td><td><button className="icon-btn" onClick={()=>go('/inventory/'+c.id)} aria-label={`Ouvrir ${c.code}`}><Icon name="right" size={18}/></button></td></tr>)}</tbody></table></div>}</>;
}
export function Repairs({query}:{query:URLSearchParams}){
 const {data,transact,go,edit}=useApp();const [search,setSearch]=useState(''),[stage,setStage]=useState(query.get('stage')||'all'),[priority,setPriority]=useState('all'),[closed,setClosed]=useState(query.get('view')==='closed'),[view,setView]=useState<'board'|'list'>('board'),[over,setOver]=useState('');
 useEffect(()=>{setStage(query.get('stage')||'all');setClosed(query.get('view')==='closed');},[query.toString()]);
 const filtered=data.repairs.filter(r=>{const c=data.consoles.find(c=>c.id===r.consoleId)!;return (!closed||!active(r))&&(stage==='all'||stage===r.stage)&&(priority==='all'||r.priority===priority)&&`${r.code} ${r.title} ${r.symptoms} ${c.model} ${c.brand}`.toLowerCase().includes(search.toLowerCase());});
 const boardStages=STAGES.filter(s=>(stage==='all'?closed?['terminee','irreparable','abandonnee'].includes(s.id):!['irreparable','abandonnee'].includes(s.id):s.id===stage));
 function move(id:string,target:Stage){transact(s=>moveRepair(s,id,target),'Étape de réparation mise à jour.');setOver('');}
 return <><PageHeader eyebrow="L’ATELIER" title="Un suivi à chaque étape." description={`${data.repairs.filter(active).length} réparations en cours · Du premier diagnostic au dernier test.`}><button className="btn primary" onClick={()=>edit({type:'repair'})}><Icon name="plus" size={18}/>Nouvelle réparation</button></PageHeader>
 <div className="view-tabs"><button className={!closed?'active':''} onClick={()=>{setClosed(false);setStage('all');}}>Tableau de suivi<span>{data.repairs.filter(r=>!['irreparable','abandonnee'].includes(r.stage)).length}</span></button><button className={closed?'active':''} onClick={()=>{setClosed(true);setStage('all');}}>Dossiers clôturés<span>{data.repairs.filter(r=>!active(r)).length}</span></button></div>
 <div className="toolbar"><div className="search-field"><Icon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un dossier…" aria-label="Rechercher les réparations"/></div><select aria-label="Filtrer les étapes" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">Toutes les étapes</option>{STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><select aria-label="Filtrer la priorité" value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">Toutes les priorités</option>{Object.entries(PRIORITIES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="segmented labeled"><button className={view==='board'?'active':''} onClick={()=>setView('board')}><Icon name="dashboard" size={16}/>Kanban</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><Icon name="list" size={17}/>Liste</button></div></div>
 {view==='board'?<><div className="kanban-instruction"><Icon name="info" size={15}/>Déplacez les dossiers entre les colonnes, ou utilisez le menu d’étape sur chaque carte.</div><div className="kanban-wrap"><div className="kanban-board">{boardStages.map(st=>{const list=filtered.filter(r=>r.stage===st.id).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));return <section key={st.id} className={`kanban-column ${over===st.id?'drag-over':''}`} onDragOver={e=>{e.preventDefault();setOver(st.id);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver('');}} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData('text/plain'),st.id);}}><div className="kanban-column-head"><span className={`stage-dot ${st.color}`}/><h2>{st.short}</h2><span className="count-bubble">{list.length}</span></div><div className="kanban-cards">{list.map(r=>{const c=data.consoles.find(c=>c.id===r.consoleId)!;return <article draggable className="repair-card" key={r.id} onDragStart={e=>{e.dataTransfer.setData('text/plain',r.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setOver('')}><div className="repair-card-top"><span className="mono">{r.code}</span><PriorityBadge priority={r.priority}/></div><button className={`repair-card-visual art-${c.illustration}`} onClick={()=>go('/repairs/'+r.id)} aria-label={`Ouvrir ${r.code}`}><ConsoleVisual item={c} small/></button><div className="repair-card-brand">{c.brand}</div><button className="repair-card-title" onClick={()=>go('/repairs/'+r.id)}>{c.model}</button><p>{r.title}</p><div className="repair-card-meta"><span className={overdue(r)?'overdue':''}><Icon name="calendar" size={13}/>{r.dueDate?dateFmt(r.dueDate).replace(/\s\d{4}$/,''):'Sans échéance'}</span><span><Icon name="clock" size={13}/>{minutesFmt(totalMinutes(r))}</span></div><select aria-label={`Changer l’étape de ${r.code}`} className="stage-select" value={r.stage} onChange={e=>move(r.id,e.target.value as Stage)}>{STAGES.map(s=><option key={s.id} value={s.id}>{s.short}</option>)}</select></article>;})}{!list.length&&<div className="kanban-empty"><Icon name={st.icon} size={23}/><span>Aucun dossier</span></div>}</div>{st.id==='reception'&&<button className="kanban-add" onClick={()=>edit({type:'repair'})}><Icon name="plus" size={16}/>Ouvrir un dossier</button>}</section>;})}</div></div></>:<div className="panel">{filtered.length?<RepairRows repairs={filtered}/>:<Empty title="Aucun dossier à afficher" icon="wrench">Modifiez vos filtres ou ouvrez une nouvelle réparation.</Empty>}</div>}</>;
}
export function Parts({query}:{query:URLSearchParams}){
 const {data,edit,ask,transact}=useApp();const [search,setSearch]=useState(''),[lowOnly,setLowOnly]=useState(query.get('low')==='1');useEffect(()=>setLowOnly(query.get('low')==='1'),[query.toString()]);
 const low=data.parts.filter(p=>p.quantity<=p.threshold);const rows=data.parts.filter(p=>(!lowOnly||p.quantity<=p.threshold)&&`${p.name} ${p.reference} ${p.compatibility} ${p.category} ${p.location}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeader eyebrow="LES RESSOURCES DE L’ATELIER" title="Les bonnes pièces, au bon endroit." description="Un stock organisé pour des réparations qui avancent."><button className="btn primary" onClick={()=>edit({type:'part'})}><Icon name="plus" size={18}/>Ajouter une pièce</button></PageHeader>
 <div className="metrics three"><Metric label="Références en stock" value={data.parts.length} detail={`${data.parts.reduce((s,p)=>s+p.quantity,0)} unités disponibles`} icon="package" onClick={()=>setLowOnly(false)}/><Metric label="À réapprovisionner" value={low.length} detail="Stock inférieur ou égal au seuil" tone="orange" icon="alert" onClick={()=>setLowOnly(true)}/><Metric label="Valeur du stock" value={money(data.parts.reduce((s,p)=>s+p.quantity*p.unitCost,0))} detail="Sur la base des coûts unitaires saisis" tone="blue" icon="euro" onClick={()=>setLowOnly(false)}/></div>
 <div className="toolbar"><div className="search-field"><Icon name="search" size={18}/><input aria-label="Rechercher des pièces" placeholder="Une référence, une console compatible…" value={search} onChange={e=>setSearch(e.target.value)}/></div><label className="checkbox-label"><input type="checkbox" checked={lowOnly} onChange={e=>setLowOnly(e.target.checked)}/>Références en alerte uniquement</label></div>
 <div className="panel">{rows.length?<div className="table-scroll"><table className="data-table parts-table"><thead><tr><th>Pièce / référence</th><th>Compatibilité</th><th>Stock</th><th>Coût unitaire</th><th>Emplacement</th><th/></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><div className="table-item"><span className={`part-symbol ${p.quantity<=p.threshold?'orange':'teal'}`}><Icon name="package" size={22}/></span><div><button className="table-title" onClick={()=>edit({type:'part',id:p.id})}>{p.name}</button><small className="mono">{p.reference}</small><span>{p.category}</span></div></div></td><td><span className="muted">{p.compatibility||'Non renseignée'}</span></td><td><div className="stock-level"><strong>{p.quantity}</strong><span>unité{p.quantity!==1?'s':''}</span></div>{p.quantity<=p.threshold?<Badge tone={p.quantity===0?'red':'orange'}>{p.quantity===0?'Rupture':'Stock bas'}</Badge>:<small className="muted">Seuil : {p.threshold}</small>}</td><td>{money(p.unitCost)}</td><td><span className="cell-location"><Icon name="location" size={14}/>{p.location||'Non renseigné'}</span></td><td><div className="row-actions"><button className="icon-btn" aria-label={`Modifier ${p.reference}`} onClick={()=>edit({type:'part',id:p.id})}><Icon name="edit" size={17}/></button><button className="icon-btn danger-icon" aria-label={`Supprimer ${p.reference}`} onClick={()=>ask({title:'Supprimer cette référence ?',body:'La suppression est possible uniquement si cette pièce n’est utilisée dans aucun dossier. L’historique des réparations est préservé.',label:'Supprimer la référence',destructive:true,run:()=>transact(s=>{if(s.repairs.some(r=>r.parts.some(u=>u.partId===p.id)))throw Error('Cette pièce est utilisée dans un dossier. Sa référence doit être conservée pour la traçabilité.');s.parts=s.parts.filter(x=>x.id!==p.id);addEvent(s,`Référence ${p.reference} supprimée du stock.`,'part');},'Référence supprimée.')})}><Icon name="trash" size={17}/></button></div></td></tr>)}</tbody></table></div>:<Empty title={data.parts.length?'Aucune pièce ne correspond':'Un tiroir encore vide'} icon="package" action={<button className="btn primary" onClick={()=>edit({type:'part'})}>Ajouter une pièce</button>}>{data.parts.length?'Modifiez votre recherche ou le filtre des alertes.':'Enregistrez vos pièces détachées pour suivre leur disponibilité et leur coût.'}</Empty>}</div><p className="section-caption"><Icon name="info" size={15}/>Les pièces ajoutées à un dossier sont déduites automatiquement. Une remise en stock annule leur coût dans ce dossier.</p></>;
}
export function ActivityPage(){const {data,go}=useApp();const [search,setSearch]=useState(''),[kind,setKind]=useState('all'),[limit,setLimit]=useState(50);const events=data.events.filter(e=>(kind==='all'||e.kind===kind)&&`${e.text} ${data.consoles.find(c=>c.id===e.consoleId)?.model||''}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeader eyebrow="LA MÉMOIRE DE L’ATELIER" title="Chaque intervention laisse une trace." description="Admissions, diagnostics, pièces, tests : toute l’activité, au même endroit."/><div className="toolbar"><div className="search-field"><Icon name="search" size={18}/><input aria-label="Rechercher dans le journal" value={search} onChange={e=>{setSearch(e.target.value);setLimit(50);}} placeholder="Rechercher une intervention…"/></div><select aria-label="Filtrer les événements" value={kind} onChange={e=>{setKind(e.target.value);setLimit(50);}}><option value="all">Tous les événements</option>{[['created','Admissions'],['stage','Changements d’étape'],['note','Notes'],['part','Pièces et stock'],['time','Temps passé'],['test','Tests'],['photo','Photos'],['edit','Modifications'],['system','Système']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="panel activity-panel">{events.length?<><Timeline events={events} limit={limit} lookup={id=>{const c=data.consoles.find(c=>c.id===id);return c?`${c.code} · ${c.brand} ${c.model}`:'';}} onOpen={e=>go(e.repairId?'/repairs/'+e.repairId:'/inventory/'+e.consoleId)}/>{events.length>limit&&<div className="panel-footer"><button className="btn secondary" onClick={()=>setLimit(x=>x+50)}>Afficher 50 événements de plus</button></div>}</>:<Empty title="Aucun événement à afficher" icon="activity">Les nouvelles actions apparaîtront ici automatiquement.</Empty>}</div></>;
}
export function Settings(){
 const {data,transact,exportData,exportInventory,ask,notify,go}=useApp();const input=useRef<HTMLInputElement>(null),[loading,setLoading]=useState(false);const bytes=new Blob([JSON.stringify(data)]).size;
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);transact(s=>{s.settings.workshop=text(f,'workshop');s.settings.owner=text(f,'owner');s.settings.hourlyRate=number(f,'hourlyRate');if(!s.settings.workshop)throw Error('Le nom de l’atelier est obligatoire.');addEvent(s,'Paramètres de l’atelier mis à jour.','system');},'Paramètres enregistrés.');}
 async function importFile(file:File){setLoading(true);try{if(file.size>20*1024*1024)throw Error('Fichier trop volumineux (20 Mo maximum).');const parsed=validateStore(JSON.parse(await file.text()));ask({title:'Restaurer cette sauvegarde ?',body:`Le fichier contient ${parsed.consoles.length} consoles, ${parsed.repairs.length} réparations et ${parsed.parts.length} références. Il remplacera intégralement les données actuelles. Exportez votre atelier avant de continuer.`,label:'Remplacer les données',destructive:true,verify:'RESTAURER',run:()=>{const ok=transact(s=>{Object.assign(s,parsed);addEvent(s,'Atelier restauré depuis une sauvegarde JSON.','system');},'Sauvegarde restaurée.');if(ok)go('/dashboard');return ok;}});}catch(e){notify(e instanceof Error?e.message:'Fichier illisible.',true);}finally{setLoading(false);if(input.current)input.current.value='';}}
 function reset(demo:boolean){ask({title:demo?'Recharger l’atelier de démonstration ?':'Commencer avec un atelier vide ?',body:'Cette action remplacera toutes les consoles, les réparations, les photos et les pièces de cet atelier local. Exportez une sauvegarde avant de poursuivre.',label:demo?'Charger la démonstration':'Créer mon atelier vide',destructive:true,verify:'EFFACER',run:()=>{const ok=transact(s=>{const next=demo?demoStore():emptyStore();if(!demo)next.settings={...s.settings,demo:false,lastExportAt:''};Object.assign(s,next);},demo?'Atelier de démonstration rechargé.':'Votre atelier est prêt. Ajoutez votre première console.');if(ok)go('/dashboard');return ok;}});}
 return <><PageHeader eyebrow="VOTRE ATELIER, VOS RÈGLES" title="Les réglages de la clinique" description="Personnalisez votre espace et prenez soin de vos sauvegardes."/><div className="settings-grid"><Panel title="Identité de l’atelier"><form onSubmit={save}><div className="panel-body form-stack"><Field label="Nom de l’atelier *"><input name="workshop" defaultValue={data.settings.workshop} maxLength={120} required/></Field><Field label="Prénom / nom affiché"><input name="owner" defaultValue={data.settings.owner} maxLength={80}/></Field><Field label="Valorisation indicative du temps (€/h)" hint="Ce taux sert uniquement à valoriser le temps enregistré. L’application ne génère pas de factures."><input name="hourlyRate" type="number" min="0" max="1000000000" step="0.01" defaultValue={data.settings.hourlyRate} required/></Field></div><div className="panel-footer"><button className="btn primary" type="submit"><Icon name="check" size={17}/>Enregistrer</button></div></form></Panel>
 <Panel title="Sauvegarder votre atelier"><div className="panel-body"><div className="storage-summary"><span className="storage-emblem"><Icon name="database" size={28}/></span><div><strong>{(bytes/1024).toLocaleString('fr-FR',{maximumFractionDigits:0})} Ko de données locales</strong><p>{data.consoles.length} consoles · {data.repairs.length} dossiers · {data.parts.length} pièces</p></div></div><p className="settings-text">Les données sont enregistrées dans ce navigateur, sur cet appareil. Elles ne sont ni synchronisées dans le cloud ni sauvegardées sur un serveur.</p><div className="notice"><Icon name="shield" size={19}/><span>Exportez régulièrement le fichier JSON. Un changement de navigateur, d’adresse locale ou l’effacement du stockage peut rendre les données inaccessibles.</span></div><small className="last-export">Dernier export JSON : {data.settings.lastExportAt?dateFmt(data.settings.lastExportAt,true):'aucun export effectué'}</small></div><div className="panel-footer wrap"><button className="btn primary" onClick={exportData}><Icon name="download" size={17}/>Sauvegarde complète JSON</button><button className="btn secondary" onClick={exportInventory}>Inventaire CSV</button></div></Panel>
 <Panel title="Restaurer une sauvegarde"><div className="panel-body"><p className="settings-text">Importez un fichier JSON exporté par La Clinique Rétro. Sa structure, les références et les états des réparations seront vérifiés avant le remplacement des données.</p><input className="sr-only" ref={input} type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);}}/><button className="import-zone" onClick={()=>input.current?.click()} disabled={loading}><Icon name="upload" size={30}/><strong>{loading?'Vérification du fichier…':'Choisir une sauvegarde JSON'}</strong><span>Les photos et l’historique sont inclus dans la restauration.</span></button></div></Panel>
 <Panel title="Données de démonstration"><div className="panel-body"><Badge tone={data.settings.demo?'amber':'green'}>{data.settings.demo?'Démonstration active':'Atelier personnel'}</Badge><p className="settings-text">La démonstration vous permet d’explorer les consoles et les dossiers fictifs. Vous pouvez la vider pour commencer votre collection, ou la recharger à tout moment.</p><div className="button-row vertical"><button className="btn secondary" onClick={()=>reset(false)}><Icon name="plus" size={17}/>Commencer avec un atelier vide</button><button className="text-link danger-text" onClick={()=>reset(true)}><Icon name="restore" size={16}/>Recharger les données de démonstration</button></div></div></Panel></div><div className="version-card"><span className="version-cross">+</span><div><strong>La Clinique Rétro <span>v1.0.0</span></strong><p>Application locale, mono-utilisateur · Aucun compte requis · Aucun suivi publicitaire</p></div><Badge tone="teal" dot={false}>CONÇUE POUR DURER</Badge></div></>;
}
